name: "hyperliquid"

services:
  node:
    restart: unless-stopped
    build: .
    ports:
      - "3001:8001"
      - "4001:4001"
      - "4002:4002"
    volumes:
      - /opt/hl-node/data:/home/hluser/hl/data

  pruner:
    restart: unless-stopped
    build: ./pruner
    volumes:
      - /opt/hl-node/data:/home/hluser/hl/data

